[package]
name = "hawhh-calendarbot-parser"
version = "3.0.5"
license = "AGPL-3.0-or-later"
repository = "https://github.com/HAWHHCalendarBot/parser"
authors = ["EdJoPaTo <calendarbot-parser@hawhh.de>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
chrono-tz = "0.8"
notify = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
